class MessageTypes:
    NEW_TRANSACTION = "new_transaction"
    NEW_BLOCK = "new_block"
    NEW_PEER = "new_peer"
    NEW_CONTRACT = "new_contract"
    NEW_VALIDATOR = "new_validator"
    CONTRACTS = "contracts"
    PENDING_TRANSACTIONS = "pending_transactions"
    BLOCKCHAIN = "blockchain"
    GET_BLOCKCHAIN = "get_blockchain"
    GET_PENDING_TRANSACTIONS = "get_pending_transactions"
    GET_CONTRACTS = "get_contracts"
    SYNC = "sync"
    VALIDATE_NEW_BLOCK = "validate_new_block"
    GENERATE_WAIT_TIME = "generate_wait_time"
    WAIT_TIME = "wait_time"
    ADD_ELAPSED_TIME = "add_elapsed_time"
